### ISSUE TITLE
Rework  Rahta and Fasshi race lifestyles. 

### ISSUE THREAD

**Issue by DaloLorn** [Alarcarr/Rising-Star#12]
- [x] Figure out how to add Glory/Comfort meter. (Hint: Use InvasionMap.as and the Attitude monitor to figure it out.)
- [x] Figure out what the Glory/Comfort meter will do - what benefits/debuffs will be caused by various Glory/Comfort levels.
- [x] Figure out how to treat Glory/Comfort in Invasion.
- [x] Make Glory/Comfort work in the first place.
- [x] Fix Invaders so they can't become derelicts.
- [x] Fix derelicts not contributing to Rahta research, Glory, or Veterancy.
- [x] Decide if 'Glory of War' is an appropriate subtitle.
- [ ] Figure out what the hell I've forgotten to mention.
- [x] Possibly add the chance for ships to grant research, influence, special funds or defense (with possibility of defense reserve overflow!) in addition to Glory.
- [x] Figure out what *else* I've forgotten about. You know there has to be something. >.<

**Comment by DaloLorn** [comment]
Looking good so far... and I'm now positive that 'Glory of War' is better than 'War against Peace'.

**Comment by DaloLorn** [comment]
... I'm not sure if I'm not paying enough attention, or I need to drastically increase the Glory gain from killing ships... I could swear killing a size-510 Oko didn't even dent the meter, and I'm only barely maintaining a fixed position at 500 Glory away from level 3 by fighting Oko forces throughout an entire star system! >.<

**Comment by DaloLorn** [comment]
Okay, there's a major bug in here. Glory is consumed but not converted into progress for some reason.

**Comment by DaloLorn** [comment]
... Killing a seed ship catapulted me from Glory 2.5 to Glory 4. Bah. >.<

**Comment by darloth** [comment]
Are you aware your editing and commenting style make you sound like a mad scientist tinkering in the lab?

Not that that's a bad thing, necessarily :)

**Comment by DaloLorn** [comment]
Slightly aware, but so long as the only effect is amusement and possibly perceived insanity... :P

**Comment by DaloLorn** [comment]
Well, I'm satisfied that Glory has reached the point where it is no longer underpowered - I beat a pair of cheating AI.

I'm not sure about overpowered, though. Might have to find a way to tone down their late-tier Glory generation somehow.

**Comment by DaloLorn** [comment]
Alar where are youuuu?

(This seems oddly familiar. >.<)
