### ISSUE TITLE
Technicist:

### ISSUE THREAD

**Issue by Alarcarr** [Alarcarr/Rising-Star#13]
- [x] Balance Shields

- [x] Replaced Techs by dalo

- [x] More Designs

- [x] Shielding Orbital need to be back.

- [x] Fix Current Desings for different goverments

**Comment by DaloLorn** [comment]
'Shielding Orbital'?

**Comment by Alarcarr** [comment]
THe orbital that regen shields in the system.

**Comment by DaloLorn** [comment]
That one's ready, I think?

**Comment by Alarcarr** [comment]
Yes.Just standard balance.
