### ISSUE TITLE
New Goverment based on SR1 research tree

### ISSUE THREAD

**Issue by Alarcarr** [Alarcarr/Rising-Star#14]
- [ ] Clone all techs related

- [ ] Iterate a system that can coexist  with the current content

- [ ] Make it feel like Sr1

**Comment by DaloLorn** [comment]
That. Is. A. Colossal. Undertaking.

It doesn't help at all that I don't even [I]have[/I] SR1... coding that system will be pretty difficult in and of itself, and from what I understand, the system's ability for runaway supertech was not too well-received.

**Comment by Alarcarr** [comment]
I can handle all of this if I  need some help, i will ask for it nevertheless
