### ISSUE TITLE
Integration of Hiigaran Shipset

### ISSUE THREAD

**Issue by Alarcarr** [Alarcarr/Rising-Star#15]
Port all model and textures:

- [ ] Using basic shader

- [ ] Using PBR one

**Comment by DaloLorn** [comment]
Basic *and* PBR shader?

If you give me all the assets, I can easily take care of the non-PBR variant and get it done pretty quickly. PBR... you'll have to talk to Jon. *A lot.* Or wait for the modding shader to come out.

**Comment by Alarcarr** [comment]
I can do the Basic as fast as u cant ,  its rotate the models and rescale them.I know how to di it.And u already have a lot of work.

With basic and PBR , I meant will be basic shading until I improve it nothing more.

**Comment by DaloLorn** [comment]
We should probably cancel this now that dolynick's doing it.
