### ISSUE TITLE
Warheads are disconnected from tech tree, no description for juggernaut hulls

### ISSUE THREAD

**Issue by darloth** [Alarcarr/Rising-Star#22]
As text above really - there's some nodes around Warheads that are not connected to the rest of the tech tree, and also nearby the Juggernaut hull type has no name or description on the tech tree itself.

**Comment by DaloLorn** [comment]
1. That needs investigating.

2. Known issue, I'm waiting for Alar to finish his part of the work there.

**Comment by darloth** [comment]
They're at the bottom of the (heralds) grid, slightly to the right.

**Comment by Alarcarr** [comment]
I close this since i fix the broken tech tree and the rest should be discussed in #18 _Bring sanity to Self Destruction Devices_
