### ISSUE TITLE
HullStrenght

### ISSUE THREAD

**Issue by darloth** [Alarcarr/Rising-Star#23]
Should be "Hull Strength", probably?  In the ship designer, possibly elsewhere.

![Example](http://puu.sh/oVPKr/5b81e5b276.jpg)

**Comment by DaloLorn** [comment]
*nods*

At some point I should really fix the underlying concept before I localize it.

**Comment by Alarcarr** [comment]
Ya as dalo said we need a function to add to this thing right is just there as a reminder it has to be done.The locale now its not that important

**Comment by Alarcarr** [comment]
We are schoolars guys we know / * but not + -.Return to school xD

**Comment by DaloLorn** [comment]
You can make a 'dummy' stat like the ones I used to calculate the estimated strength value. I just need to figure out what kind of strength formula I want to use first.

**Comment by DaloLorn** [comment]
What kind of formula do we want to use for strength?

**Comment by Alarcarr** [comment]
I think the total strengh is shieldstr+hullstr

**Comment by DaloLorn** [comment]
Which tells me absolutely none of the things I need.
