### ISSUE TITLE
Rebuild nebulae.

### ISSUE THREAD

**Issue by DaloLorn** [Alarcarr/Rising-Star#3]
- [x] Radiation Nebula
  - [x] Mono and Remnants are immune.
- [x] Pretiosian Nebula
  - [x] Allow construction of a handful of orbitals producing a small amount of money?
- [x] Interstellar Gas Cloud
- [x] Empty Space
- [x] Mutara-class Nebula
- [x] Tachyon Nebula
  - [x] Allow construction of a handful of orbitals producing a small amount of FTL Energy?
- [x] Metreon Nebula
- [x] Sicutmarian Nebula
- [x] Metaphasic Nebula
- [x] Make nebulae grant trade to adjacent empires as if they were part of their territory.

Any suggestions for new nebulae?

**Comment by DaloLorn** [comment]
Should I get started on this or something? xD

**Comment by Alarcarr** [comment]
I think this is better for 1.1 not first release .
We need need to first make sure that pacifist and berseker work.

**Comment by DaloLorn** [comment]
Eh, I'll probably manage to drop this in after Glory is implemented.

**Comment by Alarcarr** [comment]
If the IA is not told about nebulas default setting should be off.

**Comment by DaloLorn** [comment]
Can't control them yet. Don't have the code.

**Comment by DaloLorn** [comment]
This is finished.
