### ISSUE TITLE
The People want better mining vessels.

### ISSUE THREAD

**Issue by darloth** [Alarcarr/Rising-Star#30]
[Speaking about what they wanted in the new ABEM](3:31:37 AM) dada11dada22: Darloth: also what im really hoping for is to be able to create mining ships that dont suck as much as regular SR2
(3:46:07 AM) Darloth: dada11dada22: So how do the mining ships suck, and how are you hoping they'll be improved?
(3:47:05 AM) dada11dada22: idk, i would like them bigger and cheaper. also probaly wont be delt with by them is the setting automine and drop off locations always seem to bug out on me
(3:47:32 AM) dada11dada22: i have to baby sit them otherwise everyonce in the while they just stop in the middle and sit thre
(3:49:01 AM) dada11dada22: more ship types like destroyer/titan maybe we can get a support ship type agian. plus all the other stuff abem does

**Comment by DaloLorn** [comment]
Sounds like the Miner Hull needs to make a comeback...

Personally, I think we should use the pre-nerf version - there's a lot of support ship types that probably wouldn't be built at all without that thing, and it'll encourage more widespread use of the existing support ships, like tugs and scouts.

**Comment by darloth** [comment]
I agree, honestly - miners ARE a bit boring.

I was using Nylli motherships to mine recently and I realized that having almost no cargo capacity limit was really, really nice.  It made mining ships feel worthwhile.

**Comment by Alarcarr** [comment]
Miners need to be better but also give ore more uses.

**Comment by DaloLorn** [comment]
You're back! :D

**Comment by darloth** [comment]
Ore is annoying to move from place to place, so I'm unsure about most planetary improvements using it.  I wholly support certain subsystems or perhaps hull types using it - maybe Destroyers should need it?

**Comment by Alarcarr** [comment]
Only solutiion to that is make ore a global resource /look for another use for ore,

**Comment by darloth** [comment]
I'd be fine with it becoming a global resource as soon as it hits a planet, honestly.  I don't really see the benefit of tracking ore count on planets/shipyards/star forges separately.

It can stay as a ship-based resource for the purposes of mining, construction bays, etc.

**Comment by Alarcarr** [comment]
I added the Miner Hull the game.

**Comment by Alarcarr** [comment]
- [ ] More uses for ore.

**Comment by DaloLorn** [comment]
Put the Ore thing in another issue if it's still a problem. This issue was about miners, which have been solved.
