### ISSUE TITLE
Redo shields, armor and civilian buildings - and add some new weapons.

### ISSUE THREAD

**Issue by DaloLorn** [Alarcarr/Rising-Star#6]
- [x] Shields.
- [x] Armor (Flagships).
- [x] Armor (Supports).
- [x] Civilian buildings.
- [x] Weapons (Flagships).
- [x] Weapons (Supports).

**Comment by DaloLorn** [comment]
- [ ] Equipment.

**Comment by darloth** [comment]
I looked over Armor, made up some numbers pretty much whole cloth, and have an initial balance pass for them.  I've made a copy of the armor balance sheet so you can fiddle with the one already there if you want, but I've also got comments explaining most rationale.  

Have a look and tell me if you think it's a good initial set to work from please?

**Comment by darloth** [comment]
Well, now I know Github doesn't let you have multiple assignees!

**Comment by Alarcarr** [comment]
Better nnow!

**Comment by darloth** [comment]
You've ticked armor, but it's not checked in yet ;)

**Comment by DaloLorn** [comment]
Fair point. *shrugs*

**Comment by darloth** [comment]
It is now checked in for flagships at least.
