### ISSUE TITLE
Logistics mechanic discounts are reset after loading game

### ISSUE THREAD

**Issue by BottledByte** [Alarcarr/Rising-Star#85]
Build and maintenance cost discounts provided by logistics mechanic after building several ships of the same design get reset after saving and loading the game.

Found in commit 61e21ee0201440d7b88028254a6b3f20760e35cd

Screenshot at the time of save:

![before](https://user-images.githubusercontent.com/62666666/184503719-6fe9c049-1a58-415f-93e1-d20d4a1bd803.png)

After loading (Net budget and Scout cost are different):

![after](https://user-images.githubusercontent.com/62666666/184503718-24fb22db-1ff6-4b3e-a3e2-2c938ce73dfb.png)

## Reproduction steps

1. Start a new game in singleplayer
2. Build a lots of Scouts, so that logistics mechanic kicks in quickly
3. Save the game
4. Reload
5. Build and maintenace costs of existing and new Scouts are reset
  to values before logistics mechanic discounts

## Additional notes

I have skimmed through the scripts and tried to figure out the reason and it appears that the `DesignManager` object is not saved and loaded along with `ObjectManager`.

Adding `DesignManager` to `save()` and `load()` methods of `ObjectManager` seemingly fixed the issue, but I am not sure if it is a correct solution.

**Comment by DaloLorn** [comment]
... How could I miss something as big as *that?!* 😱

Yeah, it's the correct solution. Shouldn't be too hard, just have to get around to it tomorrow or something.

**Comment by DaloLorn** [comment]
Mmm, I can't think of any versioning mechanism available to me that would salvage the savefile... and it occurs to me that the Launchpad won't be able to roll back to the preceding commit on its own. Ouch. That's a bit of functionality I hadn't considered before...

You should be able to keep playing your if you manually install the right version, though.

**Comment by DaloLorn** [comment]
There's not really any convenient place to put it, as far as I know... 😐
