### ISSUE TITLE
Ancient Developer and Reinforcer effects do not match descriptions

### ISSUE THREAD

**Issue by BottledByte** [Alarcarr/Rising-Star#86]
Ancient lifestyle buildings `Developer` and `Reinforcer` descriptions mention following *bonuses*:
1. Developer - **+5%** to Support Capacity
2. Reinforcer - **+7%** to Repair Rate

Actual bonuses seem to be however:
1. Developer - **+105%** to Support Capacity
2. Reinforcer - **+107%** to Repair Rate

Found in commit 8262f9f991be52a7d7fc451b571cce8f91c7cc8f

## Additional notes

It appears to me that bonuses provided by these buildings should be those written in their descriptions, as otherwise building just a few Developers and Reinforcers makes Ancient ships *orders of magnitude more powerful* than ships of other lifestyles.

I was able to fix this by decreasing factors added by those buildings by 1, ie. from 1.05 to 0.05.

I am not sure if the increased mass malus by those buildings is subject to the same issue.

**Comment by DaloLorn** [comment]
Prooooobably not. I'll take a look...

**Comment by Skeletonxf** [comment]
CE implementation is definitely multiply by 1.0x so it is strange to see the RS port use addition here https://github.com/DaloLorn/Rising-Stars/blob/master/Rising%20Stars/data/statuses/traits/ancient/AncientReinforcer.txt

**Comment by DaloLorn** [comment]
The use of AddFactor was intended to bring it in line with the linear scaling of the RS tech grid. Unfortunately, I forgot that it requires a slightly different formula.
