### ISSUE TITLE
Rahta Issues 

### ISSUE THREAD

**Issue by Alarcarr** [Alarcarr/Rising-Star#9]
Rahta(berskers ) is a Race only being able/mainly  to generate/generating research with HOSTILE actions

With research(read all calm @DaloLorn , if my ideas dont work will go with yours but your is not optimal )  only being given by destroying ships they have a problem  some problems we need to address.

- [x] We need a multiplier for Support Ship Flags  Destroyers/Stations.
 Supports are easier to destroy than flags and destroyers even harder.So we need that mupliyer to make  balance as we go.

- [ ] Turtling on MP games need to be adressed .Enemys will have this chance  and deniying Bersekers research so again on the fly we need to make any kind of adjustment to assure they have a chance against this if well played:

- Give them research for one of any combination of (Killing Civialian ships  , civ trade stations , Colony Ships(atm  the civs  give  $k money) 

- Giving research for sieging or any trackeable magnitude u can use for that

- Adding a remnant systems next to their homeword spamming remnants periodically each time stronger.

-Any other combat  event is worth a notice.

-And finnaly the spionage one that will require a  lot of work and its better to address much later .After all base content i not broken balance wise.

**Comment by DaloLorn** [comment]
Closed, my ass.

**Comment by Alarcarr** [comment]
You handling this on another issue i close this.

**Comment by DaloLorn** [comment]
*nods*
